import {expect, test, type Page} from '@playwright/test'
import {fileURLToPath} from 'node:url'

const heading = '¿Tienes algún archivo relacionado con lo ocurrido?'
const fixture = fileURLToPath(new URL('./fixtures/captura.png', import.meta.url))
async function login(page:Page, email = 'ana@example.test') {
  await page.getByLabel('Correo electrónico').fill(email)
  await page.getByLabel('Contraseña').fill(process.env.DEMO_PASSWORD || 'Vera-Ficticia-2026!')
  await page.getByRole('button', {name:'Ingresar a mi espacio'}).click()
  await expect(page.getByLabel('Te leemos')).toBeVisible()
}
async function start(page:Page) {
  await page.goto('/'); await login(page)
  await page.getByLabel('Te leemos').fill(`Relato ficticio HU-06 ${Date.now()}`)
  await page.getByRole('button', {name:'Continuar',exact:true}).click()
  await expect(page.getByRole('heading', {name:heading})).toBeVisible()
  await expect(page.getByRole('button', {name:'Continuar sin archivos'})).toBeVisible()
  return page.url().split('/registros/')[1].split('/')[0]
}

test('HU-06: paso opcional, archivo correcto, volver al relato, quitar y aislamiento', async ({page}) => {
  const rid = await start(page)
  await page.screenshot({path:test.info().outputPath('archivos-paso-vacio.png'),fullPage:true})
  await page.getByRole('button', {name:'Añadir archivo'}).click()
  await expect(page.getByRole('button', {name:'Continuar sin archivos'})).toBeDisabled()
  await page.getByLabel('Archivo', {exact:true}).setInputFiles(fixture)
  await page.getByRole('checkbox').check()
  await page.getByRole('button', {name:'Subir archivo',exact:true}).click()
  await expect(page.getByRole('heading', {name:'captura.png',exact:true})).toBeVisible()
  const path = `/api/records/${rid}/files`
  const first = (await (await page.request.get(path)).json()).items[0]
  expect(first.account_ids).toHaveLength(1)
  await page.getByRole('button', {name:'Ver vista previa'}).click()
  await expect(page.getByRole('img', {name:'Vista previa de captura.png'})).toBeVisible()
  await page.getByRole('button', {name:'Cerrar vista previa'}).click()
  await page.getByRole('button', {name:'Volver al relato'}).click()
  await page.getByRole('button', {name:'Editar relato 1'}).click()
  await expect(page.getByRole('button', {name:'Volver a los archivos'})).toBeDisabled()
  await page.getByLabel('Descripción del hecho').fill('Relato ficticio corregido al volver')
  await page.getByRole('button', {name:'Guardar cambios del relato'}).click()
  await expect(page.getByText('Relato guardado.')).toBeVisible()
  await page.getByRole('button', {name:'Volver a los archivos'}).click()
  await expect(page.getByRole('heading', {name:'captura.png',exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', {name:'captura.png',exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:test.info().outputPath('archivos-paso-movil.png'),fullPage:true})
  await page.getByRole('button', {name:'Quitar archivo',exact:true}).click()
  await page.getByRole('button', {name:'Conservar archivo'}).click()
  await page.getByRole('button', {name:'Quitar archivo',exact:true}).click()
  await page.getByRole('button', {name:'Sí, quitar archivo'}).click()
  await expect(page.getByRole('button', {name:'Continuar sin archivos'})).toBeVisible()
  expect((await page.request.get(`${path}/${first.id}/content`)).status()).toBe(404)
  await page.getByRole('button', {name:'Añadir archivo'}).click()
  await page.getByLabel('Archivo', {exact:true}).setInputFiles(fixture)
  await page.getByRole('button', {name:'Subir archivo',exact:true}).click()
  await page.getByRole('button', {name:'Continuar con archivos'}).click()
  await expect(page.getByText('Relato ficticio corregido al volver', {exact:true})).toBeVisible()
  const file = (await (await page.request.get(path)).json()).items[0]
  await page.getByRole('button', {name:'Cerrar sesión'}).click()
  await login(page,'bea@example.test')
  await page.goto(`/#/registros/${rid}/archivos`)
  await expect(page.getByRole('alert')).toContainText('No pudimos abrir este registro')
  await expect(page.getByRole('heading', {name:'captura.png',exact:true})).toHaveCount(0)
  for (const suffix of ['', '/content','/preview']) expect((await page.request.get(`${path}/${file.id}${suffix}`)).status()).toBe(404)
})

test('HU-06: fallos comprensibles, reintento y continuar sin archivos', async ({page}) => {
  const rid = await start(page)
  await page.getByRole('button', {name:'Añadir archivo'}).click()
  await page.getByLabel('Archivo', {exact:true}).setInputFiles({name:'falso.png',mimeType:'image/png',buffer:Buffer.from('Contenido ficticio no válido')})
  await page.getByRole('button', {name:'Subir archivo',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Archivo inválido o dañado')
  await page.screenshot({path:test.info().outputPath('archivos-error-carga.png'),fullPage:true})
  await page.getByRole('button', {name:'Cancelar archivo'}).click()
  await page.getByRole('button', {name:'Añadir archivo'}).click()
  await page.getByLabel('Archivo', {exact:true}).setInputFiles(fixture)
  await page.getByRole('button', {name:'Subir archivo',exact:true}).click()
  await page.getByRole('button', {name:'Quitar archivo',exact:true}).click()
  await page.route('**/api/records/*/files/*', async route => {
    if (route.request().method() === 'DELETE') await route.fulfill({status:503,json:{detail:'Fallo controlado'}})
    else await route.continue()
  }, {times:1})
  await page.getByRole('button', {name:'Sí, quitar archivo'}).click()
  await expect(page.getByRole('alert')).toContainText('No pudimos quitar el archivo')
  await expect(page.getByRole('heading', {name:'captura.png',exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Sí, quitar archivo'}).click()
  await page.getByRole('button', {name:'Continuar sin archivos'}).click()
  await expect(page.getByRole('heading', {name:'Relatos de hechos'})).toBeVisible()
  expect((await (await page.request.get(`/api/records/${rid}/files`)).json()).items).toEqual([])
})
