import { expect, test } from '@playwright/test'

test('HU-04: borrador, reintento sin duplicados, retomar y aislamiento', async ({page}) => {
  const text = `Situación ficticia de Inicio ${Date.now()}. Quiero contar lo que recuerdo con mis propias palabras.`
  async function login(email: string) {
    await page.getByLabel('Correo electrónico').fill(email)
    await page.getByLabel('Contraseña').fill(process.env.DEMO_PASSWORD || 'Vera-Ficticia-2026!')
    await page.getByRole('button', {name:'Ingresar a mi espacio'}).click()
    await expect(page.getByRole('heading', {name:'¿Quieres contar qué ocurrió?'})).toBeVisible()
  }
  await page.goto('/')
  await login('ana@example.test')
  await page.getByLabel('Te leemos').fill(text)
  await page.reload()
  await expect(page.getByLabel('Te leemos')).toHaveValue(text)
  await page.getByRole('link', {name:'Mis registros', exact:true}).click()
  await expect(page.getByRole('heading', {name:'Mis registros'})).toBeVisible()
  await page.getByRole('link', {name:'Inicio', exact:true}).click()
  await expect(page.getByLabel('Te leemos')).toHaveValue(text)
  // Pérdida real de la respuesta después de que la API confirme su transacción.
  await page.route('**/api/start', async route => { await route.fetch(); await route.abort('failed') }, {times:1})
  await page.getByRole('button', {name:'Continuar', exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Tu texto sigue aquí')
  await page.screenshot({path:test.info().outputPath('inicio-error-guardado.png'), fullPage:true})
  await page.getByRole('button', {name:'Continuar', exact:true}).click()
  await page.getByRole('button', {name:'Continuar sin archivos', exact:true}).click()
  await expect(page.getByRole('heading', {name:'Relatos de hechos'})).toBeVisible()
  await expect(page.getByText(text, {exact:true})).toHaveCount(2)
  const records = await (await page.request.get('/api/records')).json()
  const matches = records.filter((r: {description:string}) => r.description === text)
  expect(matches).toHaveLength(1)
  const id = matches[0].id
  const accounts = await (await page.request.get(`/api/records/${id}/accounts`)).json()
  expect(accounts).toHaveLength(1)
  expect(accounts[0].date_kind).toBe('unknown')
  await page.getByRole('link', {name:'Inicio', exact:true}).click()
  await expect(page.getByLabel('Te leemos')).toHaveValue('')
  const recent = page.locator('.recent-card').filter({hasText:text})
  await expect(recent).toBeVisible()
  await page.screenshot({path:test.info().outputPath('inicio-recientes-escritorio.png'), fullPage:true})
  await recent.click()
  await expect(page.getByText(text, {exact:true})).toHaveCount(2)
  await page.reload()
  await expect(page.getByText(text, {exact:true})).toHaveCount(2)
  await page.getByRole('link', {name:'Inicio', exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await expect(page.locator('.recent-card').filter({hasText:text})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:test.info().outputPath('inicio-recientes-movil.png'), fullPage:true})
  await page.getByLabel('Te leemos').fill('Borrador ficticio que se elimina al cerrar sesión')
  await page.getByRole('button', {name:'Cerrar sesión'}).click()
  await login('bea@example.test')
  await expect(page.getByLabel('Te leemos')).toHaveValue('')
  expect((await page.request.get(`/api/records/${id}`)).status()).toBe(404)
  await expect(page.locator('.recent-card').filter({hasText:text})).toHaveCount(0)
  await page.getByRole('button', {name:'Cerrar sesión'}).click()
})

test('HU-04: revisión visual de carga, error y vacío mediante fallos controlados', async ({page}) => {
  let release!: () => void
  const waiting = new Promise<void>(resolve => {release = resolve})
  let phase = 'loading'
  await page.route('**/api/records', async route => {
    if (phase === 'loading') await waiting
    if (phase === 'error') await route.fulfill({status:503, json:{detail:'Fallo controlado de prueba'}})
    else await route.fulfill({json:[]})
  })
  await page.goto('/')
  await page.getByLabel('Correo electrónico').fill('ana@example.test')
  await page.getByLabel('Contraseña').fill(process.env.DEMO_PASSWORD || 'Vera-Ficticia-2026!')
  await page.getByRole('button', {name:'Ingresar a mi espacio'}).click()
  await expect(page.getByText('Cargando tus registros…')).toBeVisible()
  await page.screenshot({path:test.info().outputPath('inicio-carga.png'),fullPage:true})
  phase = 'error'; release()
  await expect(page.getByRole('alert')).toContainText('No pudimos cargar tus registros')
  await page.screenshot({path:test.info().outputPath('inicio-error.png'),fullPage:true})
  phase = 'empty'
  await page.getByRole('button', {name:'Reintentar registros'}).click()
  await expect(page.getByText('Este espacio empieza contigo')).toBeVisible()
  await page.screenshot({path:test.info().outputPath('inicio-vacio-escritorio.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:test.info().outputPath('inicio-vacio-movil.png'),fullPage:true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', {name:'Cerrar sesión'}).click()
})
